// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group3API.Models
{
    public partial class Status
    {
        public string ClassStatusCode { get; set; }
        public string StatusName { get; set; }
        public string StatusDescription { get; set; }
    }
}